/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:52f58f2f-fdd8-4120-92f0-62bb21636f70",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_EqrHo2f5c",
    "aws_user_pools_web_client_id": "47sc4krtckdrin3utuv1150b8u",
    "oauth": {},
    "aws_user_files_s3_bucket": "citizenwatch063fe68b078c4f1fb86f5a9ff60930d632441-staging",
    "aws_user_files_s3_bucket_region": "ap-southeast-2",
    "aws_dynamodb_all_tables_region": "ap-southeast-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "photo_metadata-staging",
            "region": "ap-southeast-2"
        }
    ]
};


export default awsmobile;
